---
version: '3'
services:
  kutsatira:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000"
    environment:
      DATABASE_URL: postgresql://kutsatira:kutsatira@db:5432/kutsatira
      DATABASE_TYPE: postgresql
      EVENTSTORE_URL: esdb://eventstore:2113?tls=false
      HASH_SALT: replace-me-with-a-random-string
    depends_on:
      - db
      - eventstore
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:app.appkutsatira.cloud"
      - "traefik.basic.port=3000"
      - "traefik.basic.protocol=https"
    restart: always

  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: kutsatira
      POSTGRES_USER: kutsatira
      POSTGRES_PASSWORD: kutsatira
    ports:
      - "5432"
    volumes:
      - ./sql/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - kutsatira-db-data:/var/lib/postgresql/data
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:db.appkutsatira.cloud"
      - "traefik.basic.port=5432"
      - "traefik.basic.protocol=https"
    restart: always
  
  eventstore:
    image: eventstore/eventstore:21.10.0-buster-slim
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "1113:1113"
      - "2113:2113"
    networks:
      - web
      - default
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:events.appkutsatira.cloud"
      - "traefik.basic.port=2113"
      - "traefik.basic.protocol=https"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore


  traefik:
    image: traefik:v1.7.16
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    container_name: traefik
    depends_on:
      - kutsatira

networks:
  web:
    external: true

volumes:
  kutsatira-db-data:
  eventstore-volume-data:
  eventstore-volume-logs:


